### ISSUE TITLE
Support a fullscreen bootstrap modal mode or action

### ISSUE THREAD

**Issue by JavaTMP** [JavaTMP/bootstrap-modal-wrapper#4]
Add a new feature to support a fullscreen mode of the modal as fixed with modal-header in the top and modal-footer on the bottom. the following links provides a good information about it:
https://codepen.io/andreivictor/pen/KXNdoO
https://codepen.io/yewnork/pen/Kpaqeq
https://codepen.io/benallfree/pen/vyxqGM
https://www.bootply.com/1HAtazFWpR
http://jsfiddle.net/8XdVt/show/
https://stackoverflow.com/questions/18432394/how-to-make-twitter-bootstrap-modal-full-screen

**Comment by JavaTMP** [comment]
Add the following styles:
```CSS
.bootstrap-modal-wrapper-fullscreen {
                position: fixed;
                top: 0;
                right: 0;
                bottom: 0;
                left: 0;
                overflow: hidden;
            }
            .bootstrap-modal-wrapper-fullscreen .modal-dialog {
                position: fixed;
                margin: 0;
                width: 100%;
                height: 100%;
                padding: 0;top: 0;
                right: 0;
                bottom: 0;
                left: 0;
                max-height: 100%;
                max-width: 100%;
                display: flex;
            }
            .bootstrap-modal-wrapper-fullscreen .modal-dialog .modal-content {
                height: 100vh;
                max-height: 100vh;
                overflow: hidden;
            }
            .bootstrap-modal-wrapper-fullscreen .modal-dialog .modal-content .modal-header,
            .bootstrap-modal-wrapper-fullscreen .modal-dialog .modal-content .modal-footer {
                flex-shrink: 0;
            }
            .bootstrap-modal-wrapper-fullscreen .modal-dialog .modal-content .modal-body {
                overflow-y: auto;
            }
```
and apply the class `bootstrap-modal-wrapper-fullscreen` to `modal` class or remove it by the following:
```JS
var dialog = BootstrapModalWrapperFactory.createModal({ ... });
$(dialog.originalModal).addClass("bootstrap-modal-wrapper-fullscreen");
dialog.show();
```
